version: '3'
services:
  db:
    image: 'postgres:11'
    container_name: simple-blog-db
    environment:
      POSTGRES_DB: simple-blog-db
      POSTGRES_USER: simple-blog-db
      POSTGRES_PASSWORD: simple-blog-db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  app:
    build: .
    container_name: simple-blog-app
    restart: always
    environment:
      - DJANGO_SECRET_KEY=local
    command: >
      bash -c "python ./manage.py migrate &&
               ./manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - '8000:8000'
    depends_on:
      - postgres

volumes:
  postgres_data:
