site_name: simple-blog
site_description: Simple blog app with Django Rest Framework
repo_url: https://github.com/danielcoker/simple-blog-drf
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/danielcoker">danielcoker</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
